# Generated by Django 3.2.25 on 2024-07-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bundle_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
