# Generated by Django 3.2.25 on 2024-07-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_sizes',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
